import { aprilAuditSchema, debtPlanSchema, portfolioSchema } from "./schema";

const portfolioRaw = {
  asOf: "2026-04-19",
  accounts: [
    {
      issuer: "Thai Credit",
      name: "Thai Credit Loan",
      statementDate: "2026-03-31",
      dueDate: "2026-04-15",
      balance: 163644.35,
      minimumDue: 4909.33,
      limit: 180000,
      note: "Largest balance and the highest line usage at 90.91% utilization.",
    },
    {
      issuer: "UOB",
      name: "UOB Credit Card",
      statementDate: "2026-03-17",
      dueDate: "2026-04-08",
      balance: 113843.52,
      minimumDue: 29206,
      limit: 430000,
      note: "Main finance-cost driver, with installment principal and interest both visible this cycle.",
    },
    {
      issuer: "UOB",
      name: "UOB Cash Card",
      statementDate: "2026-03-22",
      dueDate: "2026-04-10",
      balance: 27442.62,
      minimumDue: 27442.62,
      limit: 250000,
      note: "This cycle behaved like a pay-in-full obligation.",
    },
    {
      issuer: "Krungsri",
      name: "KKC Signature",
      statementDate: "2026-03-31",
      dueDate: "2026-04-20",
      balance: 66915.99,
      minimumDue: 6512.32,
      limit: 270000,
      note: "Only readable account not yet past due as of April 19, 2026.",
    },
    {
      issuer: "CardX",
      name: "CardX1 UP2ME",
      statementDate: "2026-03-16",
      dueDate: "2026-04-05",
      balance: 22365,
      minimumDue: 22365,
      limitShown: 219000,
      note: "Mostly transfer and installment activity rather than normal retail spend.",
    },
    {
      issuer: "CardX",
      name: "CardX2 BEYOND",
      statementDate: "2026-03-16",
      dueDate: "2026-04-05",
      balance: 11503.02,
      minimumDue: 11503.02,
      limitShown: 219000,
      note: "Driven by Apple Store Ginza purchases.",
    },
    {
      issuer: "KTC",
      name: "KTC1 World Rewards",
      statementDate: "2026-03-17",
      dueDate: "2026-04-01",
      balance: 2492.5,
      minimumDue: 199.4,
      sharedLimit: 360000,
      note: "Small fresh-spend card, after the prior balance was fully cleared.",
    },
    {
      issuer: "KTC",
      name: "KTC2 World Rewards",
      statementDate: "2026-03-17",
      dueDate: "2026-04-01",
      balance: 21612.06,
      minimumDue: 13995.62,
      sharedLimit: 360000,
      note: "Fresh-spend heavy cycle, including a large Christian Louboutin charge.",
    },
  ],
};

const aprilAuditRaw = {
  sheetTotalRow: 128437,
  rows: [
    {
      description: "Water",
      sheetPaid: 80,
      verified: null,
      status: "unverified",
      statusLabel: "Sheet only",
      note: "Utility row, not part of the card statement pack.",
    },
    {
      description: "UOB Express",
      sheetPaid: 3300,
      verified: null,
      status: "unverified",
      statusLabel: "Sheet only",
      note: "No matching UOB Express statement was included in the PDFs reviewed.",
    },
    {
      description: "Thai Credit",
      sheetPaid: 5000,
      verified: 5000,
      status: "match",
      statusLabel: "Match",
      note: "Matches the payment recorded in the Thai Credit statement.",
    },
    {
      description: "Condominium Loan",
      sheetPaid: 18000,
      verified: null,
      status: "unverified",
      statusLabel: "Sheet only",
      note: "Outside the credit-card statement set reviewed here.",
    },
    {
      description: "Krungsri Visa Signature",
      sheetPaid: 6512,
      verified: 6512.32,
      status: "rounded",
      statusLabel: "Rounded",
      note: "Very close to the Krungsri minimum due, short by THB 0.32 versus the statement.",
    },
    {
      description: "UOB Cash",
      sheetPaid: 27500,
      verified: 27442.62,
      status: "rounded",
      statusLabel: "Above min",
      note: "Sheet entry is THB 57.38 above the UOB Cash statement amount.",
    },
    {
      description: "KTC World Credit Card",
      sheetPaid: 4970,
      verified: 24104.56,
      status: "paid",
      statusLabel: "Paid in full",
      note: "The sheet shows THB 4,970, but you confirmed the KTC balance was fully paid at THB 24,104.56 outside that sheet entry.",
    },
    {
      description: "UOB Privilemiles",
      sheetPaid: 29206,
      verified: 29206,
      status: "match",
      statusLabel: "Match",
      note: "Matches the minimum due from the UOB credit card statement.",
    },
    {
      description: "SCB Card Up2Me",
      sheetPaid: 33868,
      verified: 33868.02,
      status: "rounded",
      statusLabel: "Rounded",
      note: "Very close to the combined CardX due, short by THB 0.02.",
    },
  ],
};

const debtPlanRaw = {
  items: [
    {
      label: "Thai Credit Loan",
      group: "Thai Credit",
      balance: 163644.35,
      rate: 9.99,
      aprilPaid: 5000,
      note: "Keep this on minimum-only mode until the higher-rate debts are gone.",
    },
    {
      label: "UOB Privilemiles",
      group: "UOB",
      balance: 113843.52,
      rate: 15,
      aprilPaid: 29206,
      note: "Large enough to keep finance cost heavy even after the April payment.",
    },
    {
      label: "Krungsri Visa Signature",
      group: "Krungsri",
      balance: 66915.99,
      rate: 16,
      aprilPaid: 6512,
      note: "Top-rate debt with the next due date, so it becomes the first unsecured payoff target now.",
      needsReview: true,
    },
    {
      label: "UOB Cash",
      group: "UOB",
      balance: 27442.62,
      rate: 11.99,
      aprilPaid: 27500,
      note: "Looks effectively cleared if the April payment has already posted.",
    },
    {
      label: "SCB Card Up2Me / CardX",
      group: "CardX",
      balance: 33868.02,
      rate: 9.99,
      aprilPaid: 33868,
      note: "Looks effectively cleared if the April payment has already posted.",
    },
    {
      label: "KTC World Credit Card",
      group: "KTC",
      balance: 24104.56,
      rate: 16,
      aprilPaid: 24104.56,
      note: "Treated as fully paid based on your confirmation, so it drops out of the active payoff ladder.",
    },
  ],
};

export const portfolio = portfolioSchema.parse(portfolioRaw);
export const aprilAudit = aprilAuditSchema.parse(aprilAuditRaw);
export const debtPlan = debtPlanSchema.parse(debtPlanRaw);
